{ +block{fanboy-social} }
-box-facebook_
-box-twitter_
-btn-facebook\.
-btn-fb-
-btn-instagram\.
-btn-pinteres\.
-btn-social-
-btn-twitter\.
-btn-youtube-
-btn-youtube\.
-buttons-facebook\.
-buttons-twitter\.
-connect-icons\.
-facebook-15x15\.
-facebook-64-
-facebook-64\.
-facebook-btn\.
-facebook-icon-
-facebook-icon\.
-facebook-icons-
-facebook\.svg
-facebook1\.
-facebook2\.
-fb-logo\.
-fb-share\.
-follow-icon-
-follow-icons\.
-follow-us-icons\.
-followicons\.
-foot-fb\.
-foot-twitter\.
-footer-social\.
-footer-youtube-
-footer_social\.
-google-32\.
-google-icon\.
-google-plus-
-google-plus\.
-google-plus_
-googleplus\.
-googleplus_
-header-social-
-ico-google\.
-ico-twitter\.
-icon-facebook\.
-icon-fb\.
-icon-google-
-icon-gplus\.
-icon-instagram\.
-icon-linkedin\.
-icon-social-
-icon-tumblr\.
-icon-twitter\.
-icon-youtube\.
-icon_social\.
-iconFacebook\.
-iconTwitter\.
-Instagram-Button\.
-instagram-icon\.
-instagram-logo-
-instagram_logo\.
-link-fb\.
-link-social\.
-link-twtr\.
-linkd-32\.
-linkedin-16x16\.
-linkedin-32\.
-linkedin-icon\.
-Linkedin-logo-
-linkedin-rnd\.
-linkedin-s\.
-linkedin_
-nav-social-
-nav-social\.
-pinterest-64-
-pinterest-button-
-pinterest-button\.
-pinterest-icon-
-pinterest-logo\.
-pinterest\.
-pinterest_icon\.
-pintrest-icon\.
-plus_social\.
-redes-facebook\.
-redes-gplus\.
-redes-instagram\.
-redes-pinteres\.
-redes-twitter\.
-redes-youtube\.
-share-16\.
-share-button\.
-share-buttons2\.
-share-icon\.
-share-icons-
-share-icons\.
-share-sprite\.
-share-tools-
-sharebar-
-sharebuttons_
-slide-social-
-soc-sprites\.
-social-bar\.
-social-bar/
-social-btn\.
-social-buttons-
-social-facebook-
-social-facebook\.
-social-flickr\.
-social-google-
-social-icon-
-social-icon\.
-social-icons-
-social-icons\.
-social-icons\?
-social-instagram\.
-social-linked-
-social-linkedin\.
-social-media\.
-social-pinterest-
-social-popup-
-social-profiles-
-social-share/
-social-share_
-social-sidebar\.
-social-slider/
-social-sprite-
-social-sprite\.
-social-sprites\.
-social-twitter-
-social-twitter\.
-social-widget1\.
-social-you-tube\.
-social_
-socialbar\.
-socialicons\.
-socialmedia-sprite\.
-socialmediashare\.
-sprite-social-
-stumbleupon-icon-24\.
-stumbleupon_
-subscribe-social\.
-toolbar-social\.
-tumblr-64-
-Tumblr-Button\.
-twitter-15x15\.
-twitter-16x16\.
-twitter-64-
-twitter-64\.
-twitter-btn\.
-twitter-icon-
-twitter-icon\.
-twitter-rnd\.
-twitter-social\.
-twitter-white-
-twitter\.js
-twitter\.svg
-twitter1\.
-twitter14\.
-twitter2\.
-twitterbirdsprite\.
-webicon-facebook-
-webicon-linkedin-
-webicon-twitter-
-webicon-youtube-
-youtube-24x24\.
-youtube-32\.
-youtube-btn\.
-YouTube-Button1\.
-youtube-flat-
-youtube-icon-24\.
-youtube-icon\.
-youtube-s\.
\.facebookLikePopUp\.
\.fbshare\.js
\.pluckCount\.
\.shareaholic-
\.sharebar\.js
\.social\.png
\.sociallocker\.
/16x16-delicious\.
/16x16-digg\.
/16x16-mixx\.
/16x16-newsvine\.
/16x16/facebook_
/16x16/twitter\.
/18x18-reddit\.
/32_facebook\.
/32x32-facebook\.
/32x32-gplus\.
/32x32-twitter\.
/32x32-youtube\.
/32x32/facebook_
/32x32/twitter_
/45x45xfacebook-ico\.
/45x45xtwitter-ico\.
/_sharrre\.php\?
/a2a_share_
/add-mymsn2\.
/addthis-stumble\.
/addthis_horizontal\.
/addthis_widget\.
/addtoany-
/app/social\.
/article-social/.*
/assets/.*Facebook\.jpg
/assets/.*facebook\.png
/assets/.*twitter\.png
/assets/fb\.
/badge_twitter\.
/banner-social\.
/bg-share\.
/bg-social\.
/big-facebook\.
/big-twitter\.
/bookmark/fbk\.
/bookmarksite_google\.
/bottom-facebook\.
/bottom-twitter\.
/bouton-fb\.
/bouton-youtubue\.
/bt_delicious\.
/bt_share_
/btn-blog-
/btn-digg\.
/btn-facebook-
/btn-facebook\.
/btn-follow-
/btn-googleplus-
/btn-linkedin-
/btn-share-
/btn-share\.
/btn-social-
/btn-tweet\.
/btn-twitter-
/btn-twitter\.
/btn-youtube-
/btn/follow\?
/btn_facebook\.
/btn_facebook_
/btn_fb\.
/btn_google_
/btn_share_
/btn_social\.
/btn_social_
/btn_tw\.
/btnFacebook\.
/btnFoursquare\.
/btns_linkedin_
/btns_youtube_
/btnShareSprite\.
/btnsSocialMedia\.
/btnTwitter\.
/button-facebook-
/button-facebook\.
/button-fb\.
/button-linkedin-horiz\.png
/button-linkedIn\.
/button-tumblr\.
/button-twitter-
/button-twitter\.
/Button-YouTube\.
/button/follow-
/button/share\.
/button1-share\.
/button_custom_twitter\.
/button_facebook\.
/button_pinterest\.
/button_share\.
/button_social_
/button_twitter_
/Buttons-Facebook\.
/Buttons-Linkedin\.
/Buttons-Twitter\.
/buttons/.*_fb\.png
/buttons/facebook\.
/buttons/flickr\.gif
/buttons/google\.
/buttons/identica\.gif
/buttons/linkedin\.
/buttons/repostus_
/buttons/share/.*
/buttons/share_
/buttons/social-
/buttons/social_
/buttons/socials\.
/buttons/twitter\.
/buttons/youtube\.gif
/bwSocialIcons\.
/commonSprites/social/.*
/components/share/.*
/connect-facebook-
/connect-facebook\.
/connect-google-
/connect-google\.
/connect-icons-
/connect-icons_
/connect-instagram\.
/connect-twitter-
/connect-twitter\.
/connect-youtube-
/connect_icon2\.
/connect_with_us\.
/connectfb\.
/consumer/social-
/context-social\.
/crowdbooster-
/crowdbooster_
/custom-share\.
/data/twitter/.*
/default/.*/Facebook\.png
/default/.*/Twitter\.png
/delicious-32x32\.
/delicious-button\.
/delicious-icon\.
/delicious_16\.
/delicious_32\.
/delicious_64\.
/delicious_icon\.
/delicious_small\.
/design/social_
/design/socials\.
/Devart_Icon\.
/digg-46\.
/digg-icon\.
/digg\.gif
/digg\.jpg
/digg\.png
/digg_32\.
/digg_64\.
/digg_alt_16\.
/diggButton\.
/ej-socialslider/.*
/emailshare\.
/facebkiconnet/.*
/facebok-icon\.
/Facebook-128\.
/facebook-16\.
/facebook-16x16\.
/facebook-3-
/facebook-32\.
/facebook-32px\.
/facebook-32x
/facebook-85\.
/facebook-after-
/facebook-authorizer-
/facebook-big\.
/facebook-button\.
/facebook-button2\.
/Facebook-Buttons-
/Facebook-Buttons\.
/facebook-Custom\.
/facebook-follow-
/facebook-footer-
/facebook-head\.
/Facebook-Home\.
/facebook-ico\.
/facebook-icon-
/facebook-icon\.
/facebook-icon_
/Facebook-Logo-
/facebook-logo\.
/facebook-over\.
/facebook-pagelike-widget/.*
/facebook-send-button\.
/facebook-share-
/facebook-share\.
/facebook-side\.
/facebook-small\.
/facebook-space\.
/facebook-spot\.
/facebook-top\.
/facebook-v2\.
/facebook-vertical\.
/facebook\.svg
/facebook16x16\.
/facebook2\.
/facebook24x24\.
/facebook25x25\.
/facebook2_icon\.
/facebook300\.
/facebook32\.
/facebook32px\.
/facebook40\.png
/facebook48\.
/facebook72\.
/facebook80\.
/facebook_16\.
/facebook_18x18_
/facebook_24\.
/FaceBook_24x
/facebook_29\.
/facebook_30\.
/facebook_32\.
/facebook_32x
/Facebook_36\.
/facebook_42\.
/facebook_48\.
/FaceBook_48x
/facebook_64\.
/facebook_64px_
/facebook_badge-
/facebook_badge\.
/facebook_button
/facebook_follow\.
/facebook_footer\.
/facebook_header\.
/facebook_icon\.
/facebook_icon_
/facebook_like_button\.
/facebook_logo\.
/facebook_logo_
/facebook_menu_
/facebook_ppd\.
/facebook_share\.
/facebook_share_
/facebook_side_
/facebook_sidebar\.
/facebook_small\.
/Facebook_Social_
/facebook_top_icon\.
/facebookA1_
/facebookbadge\.
/facebookBtmIcon\.
/facebookBtn\.
/facebookbutton\.
/FacebookFanWidgetFrame\.
/facebookFooterIcon-
/facebookHeader\.
/facebookicn\.
/facebookIcon32\.
/facebookicon_
/FacebookiconSMALL_
/FacebookLike\?
/facebooklike_
/facebookmall\.
/facebookon\.
/facebookpin\.
/facebookPrev\.
/facebookred\.
/facebookShare-
/facebookshare\.
/facebooksmall2\.
/facebooksquare\.
/FacebookTimeline\?
/facebooktrafficdriver\.
/facebookwidget\.
/facebutton\.png
/fan-fb\.png
/farkit-btn\.
/fb-banner\.
/FB-Button\.
/fb-grey-
/fb-icn\.
/fb-ico\.
/fb-ico2\.
/fb-icon-
/fb-icon\.
/fb-like\.
/FB-logo-
/fb-logo\.
/fb-pixel\.js
/fb-share-
/fb-share\.
/fb-traffic-pop\.
/fb-traffic-pop/.*
/fb-widget\.
/FB\.Share\.
/fb2\.gif
/fb_button\.
/fb_footer\.
/fb_ico\.
/fb_icon\.
/fb_icon_
/fb_like\.
/fb_like_button\.
/fb_likegate\.
/fb_logo\.
/fb_share\.
/fb_share_
/fb_side\.
/fb_small\.
/fb_subscribe\.
/fb_teilen_
/fb_upload_
/fbfooter\.
/FBicon\.
/fblike\.
/fblikefp\.
/fbook-share-
/fbook\.png
/fbpop\.js
/fbpromo\.
/fbshare\.
/fbshare2\.
/fbsubscribe\.
/FBtwitter_
/feed_icon\.
/feedburner_64\.
/feedly\.gif
/feedly\.png
/feeds/facebook_
/feeds/twitter_
/feedSprite_
/fh_social\.
/files/.*facebook\.png
/files/.*twitter\.png
/files/facebook-
/files/social-
/files/social/.*
/files/twitter-
/flickr-32x32\.
/flickr-icon\.
/flickr_25x25\.
/flickr_icon_
/floating-social/.*
/flw-twitter\.
/follow-facebook\.
/follow-gplus\.
/follow-icon-
/follow-icons\.
/follow-linkedin\.
/follow-mobile\.
/follow-on-twitter\.
/follow-twitter-
/follow-twitter\.
/follow-us+
/follow-us-icon-
/follow-us-icons\.
/follow-us-on-
/follow-us-twitter\.
/follow-widget-
/follow-widget\.
/follow-youtube\.
/follow/Facebook-
/follow/Google+
/follow/Twitter-
/follow_bttn_
/follow_facebook\.
/follow_google\.
/follow_instagram\.
/follow_me\.
/follow_on_sprite\.
/follow_pinterest\.
/follow_sprite_
/follow_twitter\.
/follow_us-
/follow_us\.
/follow_us_
/followbar/.*
/followbutton\.
/followfacebook\.
/FollowFB-
/Followtwit-
/followtwitter\.
/followus\.
/followus_
/foot-fb\.
/foot-gplus\.
/foot-linkedin\.
/footer-facebook-
/footer-facebook\.
/footer-google-
/footer-google\.
/footer-instagram-
/footer-Instagram\.
/footer-linkedin-
/footer-linkedin\.
/footer-pintrest\.
/footer-social-
/footer-social1\.
/footer-socialmedia-
/footer-socials\.
/footer-twitter-
/footer-twitter\.
/footer-youtube-
/footer/facebook-
/footer/fb-
/footer/google-
/footer/pinterest\.
/footer/social-
/footer/social/.*
/footer/social_
/footer/twit-
/footer/twitter-
/footer/twitter\.
/footer/youtube\.
/footer_facebook\.
/footer_fb-
/footer_fb\.
/footer_fb_
/footer_myspace\.
/footer_pinterest-
/footer_social_
/footer_sociale\.
/footer_socials_
/footer_twitter\.
/footer_twitter_
/footer_youtube\.
/footerFacebookIcon\.
/footerSocialIcons\.
/footerSocialSprite\.
/footerTwitterIcon\.
/foursquare_64\.
/friendfeed\.png
/friendfeed_16\.
/fshare\.
/g+_button\.
/g-plus-icon-
/g-plus-logo-
/g-plus\.png
/g-plus16x16\.
/gadgets/Social/.*
/gfx/socials/.*
/gg-share\.
/givememydigg\.
/goog_follow\.
/Google+-Buttons-
/Google+-Buttons/.*
/google+-icon-
/google+\.png
/Google+48x
/google+color\.
/google-32x32\.
/google-icon-
/google-icon\.
/google-over\.
/Google-Plus-
/google-plus\.png
/google-plus_
/google_16\.
/google_32x
/google_64\.
/google_icon\.
/google_plus-
/google_plus\.png
/google_plus48\.
/google_plus_18x18_
/google_plus_icon\.
/google_plus_icon2\.
/google_plus_icon_
/Google_plus_logo_
/google_plus_one\.
/googleicon\.
/googlepin\.
/googleplus-
/googleplus\.png
/googleplus40\.png
/googleplus45\.
/googleplus\?
/googleplus_14\.
/googleplus_32\.
/googleplus_42\.
/googleplus_footer\.
/googleplus_icon\.
/googleplus_square\.
/googlePlusBtn\.
/googleplusicon\.
/googlePlusLogo\.
/googlesquare\.
/gp_top\.
/gplus-16\.
/gplus-16x
/gplus-64\.png
/gplus-badge-
/gplus-badge\.
/gplus-button\.
/gplus-icon\.
/gplus-logo\.
/gplus-share-
/gplus\.gif
/gplus\.jpg
/gplus\.png
/gplus\.svg
/gplus2\.gif
/gplus28\.
/gplus32\.
/gplus_16\.
/gplus_footer\.
/gplus_ico\.
/gplus_icon\.
/gplus_social_
/gplusbadge-
/gplusbtn\.
/gpluslogo-50\.
/gplusrp\.
/graphics/twitter\.
/guys_social\.
/Handlers/Sharrre\.ashx\?
/head-social\.
/head_facebook\.
/head_twitter\.
/header-facebook\.png
/header-social-
/header-twitter\.png
/header/fb-
/header/share\.
/header/twitter-
/header_fb\.
/header_social_
/header_socials\.
/headerSocialIcons\.
/highlight_share\.
/home-fb\.
/home/facebook\.
/home/twitter\.
/houzz-button\.
/ic_delicious\.
/ic_digg\.
/ic_facebook\.
/ic_reddit\.
/ic_stumbleupon\.
/ic_technorati\.
/ic_twitter\.
/icn-facebook-
/icn-facebook\.
/icn-google-
/icn-linkedin-
/icn-pinterest-
/icn-tumblr\.
/icn-twitter-
/icn-twitter\.
/icn-youtube\.
/icn_facebook_
/icn_googe_
/icn_google_
/icn_pinterest_
/icn_twitter_
/icn_youtube_
/ico-delicious\.
/ico-digg\.
/ico-facebook-
/ico-facebook\.
/ico-fb-
/ico-fb\.
/ico-google-
/ico-google\.
/ico-gplus-
/ico-instagram\.
/ico-linkedin\.
/ico-pinterest-
/ico-reddit\.
/ico-scoopit\.
/ico-share-
/ico-share\.
/ico-social-
/ico-social\.
/ico-stumble\.
/ico-technorati\.
/ico-tumblr\.
/ico-tw\.
/ico-twitter-
/ico-twitter\.
/ico-twttr-
/ico-twttr\.
/ico-youtube\.
/ico/social_
/ico_buzzurl\.
/ico_delicious\.
/ico_digg\.
/ico_facebook\.
/ico_facebook_
/ico_fb\.
/ico_fb_
/ico_google\.
/ico_google_
/ico_gp\.
/ico_instagram-
/ico_linkedin\.
/ico_myspace\.
/ico_pinterest-
/ico_pinterest\.
/ico_share\.
/ico_social-
/ico_social\.
/ico_social_
/ico_socialshare_
/ico_stumble\.
/ico_technorati\.
/ico_twitter\.
/ico_twitter_
/ico_youtube-
/ico_youtube\.
/icofacebook\.
/icogoogle\.
/icolinkedin\.
/icon-delicious-
/icon-delicious\.
/icon-digg-
/icon-digg\.
/icon-facebook-
/icon-facebook\.
/icon-facebook_
/icon-fb\.
/icon-flickr-
/icon-flickr\.
/icon-follow-
/icon-google\.
/icon-googleplus-
/icon-gplus-
/icon-gplus\.
/icon-instagram-
/icon-instagram\.
/icon-linkedin
/icon-pinterest-
/icon-reddit-
/icon-reddit\.
/icon-reddit2\.
/icon-share-
/icon-share\.
/icon-social-
/icon-social\.
/icon-stumble\.
/icon-stumbleupon-
/icon-stumbleUpon\.
/icon-technorati-
/icon-tumblr-
/icon-tumblr\.
/icon-tw\.
/icon-tweet\.
/icon-twit\.
/icon-twitter-
/icon-twitter\.
/icon-twitter_
/icon-twt\.
/icon-vimeo\.
/icon-yout\.
/icon-youtube-
/icon-youtube\.
/icon-youtube_
/icon/fb\.
/icon/google\.
/icon/share/.*
/icon/share_
/icon/twitter-
/icon2_facebook_
/icon2_instagram_
/icon2_twitter\.
/icon2_youtube\.
/icon32_facebook_
/icon32_googleplus_
/icon32_pinterest_
/icon32_twitter_
/icon_16_twitter\.
/icon_32_facebook\.
/icon_32_google\.
/icon_32_twitter\.
/icon_32_youtube\.
/icon_addthis\.
/icon_delicious\.
/icon_delicious_
/icon_digg\.
/icon_digg_
/icon_face\.
/icon_facebook\.
/icon_facebook48\.
/icon_facebook_
/icon_fb\.
/icon_fb_
/icon_google+
/icon_google\.
/icon_google_
/icon_googleplus-
/icon_googleplus_
/icon_gplus\.
/icon_gplus_
/icon_linked\.
/icon_linkedin\.
/icon_linkedin_
/icon_orkut\.
/icon_pinterest\.
/icon_pinterest_
/icon_reddit\.
/icon_reddit_
/icon_share\.
/icon_share_
/icon_sharethis_
/icon_social-
/icon_social\.
/icon_social_
/icon_stumble\.
/icon_tumblr\.
/icon_tumblr_
/icon_tw_
/icon_tweet\.
/icon_twit\.
/icon_twitt\.
/icon_twitter\.
/icon_twitter48\.
/icon_twitter_
/icon_twt\.
/icon_youtube\.
/icon_youtube_
/iconbig-twitter-
/iconFacebook-
/iconFacebook\.
/iconGooglePlus\.
/icono-facebook\.
/icono-twitter\.
/icono_google\.
/icono_twitter\.
/IconoFB\.
/iconogoogleplus\.
/IconoTW\.
/IconoYT\.
/icons-share-
/icons-social-
/icons\.social\.
/icons/delicious-
/icons/delicious_
/icons/digg-
/icons/facebook
/icons/google
/icons/gplus
/icons/instagram
/icons/linkedin_
/icons/myspace_
/icons/pinterest
/icons/reddit-
/icons/share-
/icons/share\.
/icons/Share_
/icons/sharing/.*
/icons/social-
/icons/social\.
/icons/social/.*
/icons/social_
/icons/socials\.
/icons/tumblr
/icons/twitter
/icons/weibo_
/icons/youtube
/icons_social\.
/icons_social_
/icons_socialmedia2\.
/icons_twitter_
/iconSocial\.
/iconTwitter\.
/icosocialbar\.
/icotwitter\.
/ig-socials\.
/image/social_
/images/.*/delicious\.jpg
/images/.*/social_
/images/.*_share\.png
/images/.*flickr\.jpg
/images/.*flickr\.png
/images/.*flipboard\.png
/images/.*googleplus\.gif
/images/.*googleplus\.png
/images/.*gplus\.png
/images/.*houzz\.jpg
/images/.*instagram\.gif
/images/.*instagram\.jpg
/images/.*instagram\.png
/Images/.*linkedin\.ashx
/images/.*linkedin\.jpg
/images/.*linkedin\.png
/images/.*reddit\.jpg
/images/.*steam\.png
/images/.*stumbleupon\.jpg
/images/.*tumbler\.gif
/images/.*tumbler\.jpg
/images/.*tumblr\.jpg
/images/.*twitter-
/images/.*twitter\.jpg
/images/.*twitter\.png
/images/.*youtube\.jpg
/images/.*youtube\.png
/images/facebook
/images/fb-
/images/fb\.
/images/fb_
/images/google-
/images/googleplus
/images/gplus-
/images/instagram-
/images/instagram_
/Images/linkedin
/images/reddit-
/images/share\.
/images/share/.*
/images/share_
/images/sociable/.*
/images/social-
/images/social\.
/images/social/.*
/images/socials/.*
/images/tumblr-
/images/twiter
/images/twitter
/images/youtube-
/images/youtube_
/images2/.*twitter\.png
/Images2/fb\.
/Images2/gp\.
/Images2/tw\.
/img-social-
/img/.*/flickr\.png
/img/.*/google\.png
/img/.*/social-
/img/.*/social\.gif
/img/.*/social_
/img/.*facebook\.gif
/img/.*facebook\.jpg
/img/.*facebook\.png
/img/.*google\.gif
/img/.*gplus\.jpg
/img/.*instagram\.png
/img/.*linkedin\.jpg
/img/.*linkedin\.png
/img/.*quora\.png
/img/.*tumblr\.png
/img/.*twitter\.gif
/img/.*twitter\.jpg
/img/.*twitter\.png
/img/.*youtube\.gif
/img/.*youtube\.jpg
/img/.*youtube\.png
/img/facebook-
/img/facebook\.
/img/facebook_
/img/fb\.
/img/fb_
/img/gplus_
/img/instagram-
/img/share/.*
/img/share_
/img/social-
/img/social_
/img/tumblr-
/img/twitter-
/img/twitter\.
/img/twitter_
/imgs/facebook\.
/imgs/twitter\.
/in-icon\.
/in_icon\.
/include/twitter/.*
/insta-icon-
/instagram-32px\.
/instagram-48\.
/instagram-button\.
/instagram-footer-
/instagram-icon\.
/instagram-logo-
/instagram1\.gif
/instagram_48\.
/instagram_icon\.
/Instagram_Icon_
/Instagram_logo\.
/instagram_title_
/instagramLogo\.
/itunes-icon\.
/jinda-facebook-lightbox/.*
/jquery-pin-it-
/jquery\.stp\.min\.js
/largeSocialIcons\.
/layoutsharedelicious\.
/layoutsharetechnorati\.
/layoutshareyahoo\.
/li_share\.
/liinkedInBtn\.
/like-facebook-
/like-facebook_
/like-follow\.
/like-follow_
/like-share\.
/like-us\.
/like_bttn_
/like_button\.
/likebox\.
/likegate\.js
/likeus-fb\.
/link-delicious\.
/link-digg\.
/link-facebook\.
/linked_in\.
/LinkedIn\.29x
/linkedin\.png
/linkedin\.svg
/linkedin1\.
/linkedin_16\.
/linkedin_29\.
/linkedin_32\.
/linkedin_36x
/linkedin_footer\.
/linkedin_icon\.
/linkedin_icon_
/linkedin_logo\.
/linkedin_small\.
/Linkedin_social\.
/linkedinlogo\.
/LinkedInShare\.
/linkin\.png
/linkin_icon\.
/linkind2\.
/links/facebook\.
/links/twitter\.
/links/youtube\.
/linkshare\.
/logo-facebook\.
/logo-flickr_
/logo-instagram\.
/logo-vimeo_
/logo-wordpress_
/logo_facebook\.
/logo_facebook_
/logo_fb\.
/Logo_instagram\.
/logo_tw\.
/logo_twitter\.
/logo_yt\.
/logoLinkedin\.
/logos/facebook-
/logos/facebook_
/logos/fb\.
/Logos/social_
/logos/twitter-
/logos/twitter\.
/logos/twitter_
/logoTwitter\.
/masthead/social-
/media/.*facebook\.png
/media/.*fb20\.png
/media/.*linkedin20\.png
/media/.*twitter\.png
/media/.*twitter20\.png
/media/.*youtube20\.png
/min_share\.
/mobile-sharing/.*
/mobilesharetools\.
/mod_socialmedialinks/.*
/mod_socialslider/.*
/myspace-32x32\.
/myspace-black\.
/MySpace-icon\.
/myspace_16\.
/myspace_add\.
/myspace_share\.
/myspacesmall\.
/nav-facebook-
/nav-google-
/nav-social-
/nav-twitter-
/nav_facebook\.
/nav_twitter\.
/navicon_facebook\.
/navicon_twitter\.
/navicon_youtube\.
/navtumblr\.
/nc-follow1\.
/orange-fb-
/orange-twit-
/orkut\.gif
/orkut_16\.
/outsidesocialsprite\.
/partnerNavSocialButtons\.
/pics/.*facebook\.png
/pics/.*twitter\.png
/pin-icon-
/pin-it\.gif
/pin_it_button\.
/pinit-btn\.
/pinit-button\.
/pinit\.html\?
/pinit\.png
/pinit_footer\.
/pinmask2\.
/pins/social-
/pinShare\.
/pinterest-32\.
/pinterest-32px\.
/pinterest-big\.
/pinterest-button-
/pinterest-button\.
/pinterest-button12\.
/pinterest-footer-
/pinterest-icon\.
/pinterest-icon_
/pinterest-logo-
/pinterest-logo\.
/pinterest-new-
/pinterest-over\.
/pinterest-share-
/pinterest-sidebar\.
/pinterest\.png
/pinterest1\.
/pinterest2\.
/pinterest80\.
/pinterest_64\.
/pinterest_badge_
/pinterest_icon-
/pinterest_icon\.
/pinterest_pin\.
/pinterest_tag\.
/pinterestbutton\.
/PinterestIcon\.
/pinterestsquare\.
/pintrest-button\.
/pintrest-icon\.
/pintrest\.
/pintrest_
/pix/Share-
/plain/facebook-
/plain/pinterest-
/plain/tumblr-
/plain/twitter-
/plugins/.*facebook\.png
/plugins/.*google\.png
/plugins/.*twitter\.png
/plugins/anmiated-twitter-bird/.*
/plugins/bookmarkify/.*
/plugins/delicious-bookmark-button/.*
/plugins/easy-facebook-likebox/.*
/plugins/easy-twitter-
/plugins/facebook-button-plugin/.*
/plugins/facebook-fanbox-popup/.*
/plugins/facebook-like-content-locker/.*
/plugins/facebookpopuppro/.*
/plugins/flare/js/flare\.js
/plugins/getsocial/.*
/plugins/knxdt-bookmarks-wordpress-plugin/.*
/plugins/like-box-pro/.*
/plugins/like-fb/.*
/plugins/osd-social-media-sharing/.*
/plugins/socialbox/.*
/plugins/StickySocialBar/.*
/plugins/super-socializer/.*
/plugins/tweet-this/icons/.*
/plugins/tweetmeme/.*
/plugins/ultimate-follow-me/.*
/plugins/viperbar/.*
/plugins/wordpress-social-ring/.*
/plugins/wp-plus-one/.*
/plugins/wp-share-to-xing/.*
/plugins/wp-social-toolbar-pro/.*
/plugins/wp-tweet-button/.*
/plus-badge\.
/popinfacebook\.
/popups/facebook_
/portals/.*facebook\.jpg
/portals/.*google-plus\.jpg
/portals/.*linkedin\.jpg
/portals/.*you-tube\.jpg
/printarest\.
/public/.*facebook\.png
/public/.*twitter\.png
/public/social/.*
/red-facebook-
/red-linkedin-
/red-twitter-
/reddit-icon\.
/reddit-small\.
/reddit\.png
/reddit_16\.
/reddit_32\.
/Reddit_Icon\.
/repost_bttn\.
/repostus_bttn_
/Resources/facebook\.
/retweet-button\.
/rotating_tweet\.
/rss-iconheader\.
/rtsocial/.*
/sc-twitter-
/ScoailMedia_
/scocial-
/selection-sharer\.
/seomoz_35\.
/share-addtoany\.
/share-bebo\.
/share-black\.
/share-btn-
/share-btns\.
/share-button\.
/share-button\?
/share-buttons-
/share-buttons/.*
/share-count\.
/share-delicious\.
/share-facebook-
/share-facebook\.
/share-fb-
/share-fb\.
/share-fb1a\.
/share-footer\.
/share-google\.
/share-google1a\.
/share-icon-
/share-icons-
/share-icons\.
/share-icons/.*
/share-link-
/share-media\.
/share-myspace\.
/share-on-diaspora/.*
/share-pinterest-
/share-social-networks\.
/share-sprite-
/share-sprite\.
/share-this-
/share-twitter-
/share-twitter\.
/share-twitter1a\.
/share\.json\?
/share\.png
/share/.*/facebook\.png
/share/.*/twitter\.png
/share/buttons/.*
/share/facebook\.
/share/flattr\.
/share/footer/.*
/share/google\.
/share/googlebookmarks\.
/share/icon_
/share/js/.*
/share/plusone\.
/share/share_
/share/tools_
/share/twitter\.
/share/yahoomyweb\.
/share2-
/share2\.png
/share42\.js
/share42_
/share_bebo\.
/share_blogger\.
/share_btn\.
/share_btns_
/share_button\.
/share_button\?
/share_button_
/share_buttons-
/share_byline_
/share_count\.
/share_delicious\.
/share_digg\.
/share_facebook\.
/share_facebook_
/share_fb\.
/share_googlePlus_
/Share_icn\.
/share_icon\.
/share_icon_
/share_icons\.
/share_icons/.*
/share_icons_
/share_iframe\.
/share_link/.*
/share_linkedin_
/share_myspace\.
/share_pinterest-
/share_reddit-
/share_rss\.
/share_save_
/share_sprite\.
/share_sprite_
/share_tf-
/share_toolbar\.
/share_tumblr-
/share_twitter\.
/share_twitter_
/shareaholic\.js
/shareaholic/.*
/shareamex/.*
/shareArrow\.
/sharebariconfacebook_
/sharebaricongoogle_
/sharebariconinstagram_
/sharebariconpinterest_
/sharebariconrss_
/sharebaricontwitter_
/sharebox\.
/shareBtn_
/shareButton\.
/sharebutton\?
/sharebuttons\.
/sharebuttons/.*
/sharebutts\.
/shared/btn_
/shared/social/.*
/sharedcount\.
/shareFacebook\.
/Sharefb\.
/sharefrom/.*
/ShareG+\.
/ShareOnMySpace/.*
/sharepage-
/sharePost/.*
/sharethis\.js
/sharethis_
/shareThisIcons\.
/sharetool\.php\?
/shareTools\.js
/sharetoolsnew\.
/Sharetw\.
/shareTwitter\.
/shareWidgetBackgrounds\.
/sharing-buttons\.
/sharing/sprites/.*
/SharingBar/.*
/sharrre_
/shr_btn_
/sibar-social\.
/sicons/pinterist\.
/sicons/vimeo\.
/sicons/you_tube\.
/side-facebook\.
/side-social-
/side-social/.*
/side-twitter\.
/sidebar-facebook-
/sidebar-follow\.
/sidebar-pinterest-
/sidebar-social\.
/sidebar-twitter\.
/sidebar/social/.*
/sidebar_facebook\.
/sidebar_gplus\.
/sidebar_social_
/sidebar_twitter\.
/sidenav_instagram_
/sidenav_tumblr_
/simple-social-icons/.*
/simpleshare\.js
/simplified-social-
/site/share/.*
/SiteImages/facebook\.
/SiteImages/Twitter\.
/slashdot-icon\.
/slick-social-
/slideshare-48\.
/slideshare\.png
/sm-youtube-
/small_fb\.
/small_twitter\.
/smicons/fb_
/smicons/pin-
/smicons/tw-
/sn_share_
/soc-fb\.
/soc-icons\.
/soc-lj2\.
/soc-tw\.
/soc-vk\.
/soc-yt\.
/soc_bottom_
/soc_facebook2\.
/soc_facebook_
/soc_med_
/soc_media_
/soc_twi-
/soc_twi\.
/soc_twitter2\.
/soc_twitter_
/soc_youtube_
/socbutton/.*
/sociables/.*
/social-16px-
/social-48/.*
/social-badges\.
/social-bar-
/social-bar\.
/social-bookmark\.
/social-bookmarks-generator/.*
/social-bookmarks/.*
/social-box\.
/social-btm-
/social-buttons\.
/social-buttons/.*
/social-delicious\.
/social-digg\.
/social-facebook-
/social-facebook\.
/social-fb\.
/social-footer\.
/social-g+-
/social-google\.
/social-header\.
/social-icon/.*
/social-icons-
/social-icons\.
/social-icons_
/social-instagram-
/social-instagram\.
/social-like-
/social-links-
/social-media-banner\.
/social-media-buttons\.
/social-media-icons-
/social-media-icons\.
/social-media-icons/.*
/social-media-sprite\.
/social-media2\.
/social-myspace-
/social-nav-
/social-network-icons-
/social-network\.
/social-networking/.*
/social-overlay-
/social-pinterest-
/social-proof-
/social-search-
/social-share-
/social-sharing-
/social-sharing\.
/social-signs\.
/social-sprite-
/social-sprite\.
/social-sprite_
/social-sprites-
/social-sprites\.
/social-sprites2\.
/social-traffic-pop/.*
/social-tumblr\.
/social-twit\.
/social-twitter-
/social-twitter\.
/social-youtube-
/social-youtube\.
/social-yt\.
/social\.icon\.
/social\.jpg
/social\.png
/social/bar\?
/social/facebook-
/social/facebook/.*
/social/facebook_
/social/flickr\.
/social/follow-
/social/footer_
/social/footerIcons\.
/social/foursquare_
/social/google-
/social/google\.
/social/google_
/social/gplus-
/social/gplus_
/social/icon32/.*
/social/icon_
/social/icons/.*
/social/img/.*
/social/instagram-
/social/instagram_
/social/pinterest-
/social/pinterest_
/social/plus\.
/social/share-
/social/share_
/social/shared/.*
/social/sprite-
/social/tumblr\.
/social/twitter-
/social/twitter_
/social/vimeo\.
/social1\.
/social2\.
/social3\.
/social4\.
/social_01\.
/social_02\.
/social_2\.
/social_apple
/social_badges/.*
/social_badges_
/social_black/.*
/social_bookmarking\.
/social_bookmarks/.*
/social_box/.*
/social_btns\.
/social_button\.
/social_buttons\.
/social_buttons/.*
/social_buzz\.
/social_circles_
/social_clip_icons\.
/social_delicious_
/social_digg_
/social_facebook
/social_favorites\.
/social_fb\.
/social_fb2\.
/social_flickr
/social_g2\.
/social_google-
/social_google\.
/social_google_
/social_header\.
/social_headers\.
/social_hovers\.
/social_hub/.*
/social_icon_
/social_icons-
/social_icons\.
/social_icons/.*
/social_icons_
/social_images/.*
/social_instagram-
/social_instagram\.
/social_instagram2\.
/social_large/.*
/social_linkedin\.
/social_logo_
/social_logos\.
/social_mb\.
/social_media_
/social_n_
/social_pinterest-
/social_pinterest\.
/social_pinterest2\.
/social_popup\.
/social_print\.
/social_reddit_
/social_share_
/social_small/.*
/social_sprite-
/social_sprite\.
/social_sprite_
/social_strip\.
/social_stumbleupon_
/social_subscribe_
/social_technorati_
/social_tools\.
/social_tube-
/social_tweet\.
/social_twitter
/social_vimeo2\.
/social_widget/.*
/social_widget\?
/social_youtube
/socialbadges\.
/socialbar-
/socialbar\.
/socialbar_
/socialBarSprite\.
/socialbig\.
/SocialBookmark/.*
/socialbookmarkerbot_images/.*
/socialbookmarks\.
/socialbookmarks/.*
/socialbtn\.
/socialBtns\.
/socialbutton_
/socialButtons\.
/socialbuttons/.*
/socialcount\.
/socialcounters/.*
/socialFooterSprite\.
/socialhomesprite2\.
/socialIcons-
/socialIcons\.
/socialicons/.*
/socialicons2\.
/socialicons_
/socialinstagram\.
/sociallink-
/sociallinks\.
/sociallocker-
/socialMedia-
/socialMedia\.
/socialmedia_
/socialmediabuttons\.
/SocialMediaFooter\.
/socialMediaIcon\.
/socialmediaicons\.
/socialmediaicons/.*
/socialmediaicons_
/socialMediaPinterestButton\.
/socialmediaround\.
/socialmedias\.
/socialmediasprite\.
/socialmediasprites2\.
/socialNet\.
/socialNetFooter\.
/socialnetwork-buttons/.*
/socialnetwork\.png
/socialNetworkSprite\.
/socialplugins/.*
/socialpod-
/socials\.png
/socials/flipboard-
/socials/instagram-
/socials/pinterest-
/socials_new\.
/socialshare-
/socialShare\.
/socialshare2\.
/socialshare_
/socialShareCount\.
/socialshares\.
/SocialShareSprite\.
/socialsheet\.
/socialsIcons/.*
/socialSmall/.*
/SocialSprite\.
/socialsprites\.
/socialtwitter1\.
/socila-media-
/socjal/facebook\.
/socjal/twitter\.
/SocMedIcon_
/socmedicons\.
/sp_social-
/splash/twitter\.
/spr-social\.
/sprite-share\.
/sprite-sharetools\.
/sprite-social-
/sprite-social\.
/sprite_social-
/sprite_social\.
/sprite_social_
/spriteiconshare\.
/sprites-social-
/sprites-social\.
/sprites-social2\.
/sprites/follow-
/sprites/share-
/sprites/social-
/sprites_social\.
/spriteSheetSocial\.
/spriteSocial\.
/spriteSocialIcons\.
/squaresocial-
/ss-social-
/st_add-this_
/st_digg_
/st_facebook_
/st_twitter_
/static/.*fb\.png
/stocktwits_share\.
/storage/social/.*
/story-follow\.png
/stumble_button\.
/stumble_icon\.
/stumbleupon1\.
/stumbleupon256x\.
/stumbleupon\?
/stumbleupon_16\.
/stumbleupon_32\.
/stumbleupon_badge\.
/su_small\.
/subscribe-button-
/subscribe-icons-
/subscribe_facebook\.
/subscribe_twitter\.
/technorati-icon\.
/technorati_16\.
/template/facebook_
/template/twitter_
/templates/.*facebook\.jpg
/templates/.*youtube\.jpg
/theme/Facebook_
/theme/social-
/theme/Twitter_
/theme/YouTube_
/thumbnail/.*facebook-icon\.png
/thumbnail/.*google-icon\.png
/thumbnail/.*linkedin-icon\.png
/thumbnail/.*twitter-icon\.png
/ticon_facebook\.
/ticon_pinterest\.
/ticon_twitter\.
/tiwttericon\.
/toolbar-digg\.
/toolbar-facebook\.
/toolbar_twitter\.
/top-social\.
/top_fb\.
/top_social\.
/top_social_
/touch/share-
/tube32\.
/tumbler-icon-
/tumblr-25x25\.
/tumblr-48x
/tumblr-follow\.
/tumblr-footer-
/tumblr-icon-
/tumblr-icon\.
/tumblr-logo-
/tumblr\.png
/tumblr1\.
/tumblr80\.
/tumblr_badge_
/Tumblr_Icon\.
/tumblr_logo\.
/tumblr_logo4\.
/tumblr_share\.
/tumblrbigicon\.
/tw-button3\.
/tw-ico\.
/tw-icon\.
/tw-logo\.
/tw_follow\.
/tw_footer\.
/tw_icon\.
/tw_share_
/tw_small\.
/tw_top\.
/tweet-button\.
/tweet-ico\.
/tweet\.png
/tweet_button\.
/tweet_button2\.
/tweet_footer\.
/tweetbutton\.
/tweetcount\.
/tweetgrid\.
/tweeticon-
/tweetn\.
/tweets\.js
/twfollowfp\.
/twfooter\.
/twit-button-
/twit-icon\.
/twit_icon\.
/twitbadge\.
/twitbutton\.
/twiter-icon\.
/Twiticon\.
/twitt2\.gif
/twittbutton\.png
/Twitter-1-
/twitter-16px\.
/twitter-16x
/twitter-32\.
/twitter-32px\.
/twitter-32x
/twitter-64\.
/twitter-85\.
/twitter-after-
/twitter-b\.png
/twitter-big\.
/twitter-button-
/twitter-button\.
/twitter-button2\.
/Twitter-Buttons-
/Twitter-Buttons\.
/twitter-custom-
/twitter-Custom\.
/twitter-follow-
/twitter-footer-
/Twitter-Home\.
/twitter-ico\.
/twitter-icon-
/twitter-icon\.
/twitter-icon_
/twitter-iconheader\.
/twitter-link\.
/twitter-logo-
/twitter-logo\.
/twitter-module\.
/twitter-over\.
/twitter-plugin/.*
/twitter-share-
/twitter-share\.
/twitter-small\.
/twitter-social-
/twitter-space\.
/twitter-timeline-
/twitter-v2\.
/twitter-widget-
/twitter-widget\.
/twitter\.gif
/twitter\.jpg
/twitter\.svg
/twitter/facebook_
/twitter/lookup\?
/twitter/twitter_
/twitter0\.png
/twitter16x16\.
/twitter232\.
/twitter25x25\.
/twitter2_icon\.
/twitter3\.
/twitter300\.
/twitter32\.
/twitter32px\.
/twitter3gif\.
/twitter40\.png
/twitter45\.
/twitter48\.
/twitter72\.
/twitter80a\.
/twitter_12\.
/twitter_16\.
/Twitter_16x16\.
/twitter_18x18_
/twitter_24\.
/Twitter_24x24\.
/twitter_29\.
/twitter_30\.
/twitter_32\.
/twitter_32x
/Twitter_36\.
/twitter_42\.
/Twitter_48
/twitter_64\.
/twitter_64x
/twitter_add\.
/twitter_alt\.
/twitter_badge\.
/twitter_bird\.
/twitter_bird_
/twitter_bubble_
/Twitter_button
/twitter_follow\.
/twitter_footer\.
/twitter_header\.
/twitter_ico2\.
/twitter_icon\.
/twitter_icon2\.
/twitter_icon_
/twitter_inc\.
/twitter_logo\.
/twitter_logo_
/twitter_menu_
/twitter_share\.
/Twitter_social\.
/Twitter_Social_
/twitter_sprite\.
/twitter_square\.
/twitter_subscribe\.
/twitter_title_
/twitter_top_icon\.
/twitterbadge\.
/twitterbadge/.*
/twitterbigicon\.
/twitterBtmIcon\.
/twitterBtn\.
/twitterbutton-
/twitterbutton\.
/twittered\.
/twitterFetcher_
/twitterfloat\.js
/twitterfollow\.png
/twitterfollowbadge/.*
/twittericn\.
/twitterIcon32\.
/Twittericon_
/twitterlib\.
/twitteron\.
/twitterpin\.
/twitterPrev\.
/twittersmall\.
/twittersmall2\.
/twittersquare\.
/twitterWidgetHeader\.
/twitthis_
/twt-icon\.
/twt-share\.
/twt1\.
/twt_icon\.
/twt_side\.
/twtr\.png
/twtr_icon_
/twttr\.
/UIFollow\.
/uploads/.*facebook\.jpg
/uploads/.*pinterest\.jpg
/uploads/.*rss\.png
/uploads/.*twitter\.png
/uploads/facebook-
/uploads/facebook\.
/uploads/twitter-
/uploads/youtube2\.
/utube-icon\.
/view_social_
/viewboxTraffic_min\.js
/vimeo-48\.
/vimeo-icon\.
/vimeo_32\.
/vimeo_icon_
/visual/social/.*
/vk_button\.
/vkontakte\.png
/vkontakte2_icon\.
/widget_add_this_
/Widgets/.*/Tweets\?
/widgets/twitter/.*
/wp-content/.*/google\.png
/wp-content/.*facebook\.jpg
/wp-content/.*facebook\.png
/wp-content/.*Google+\.png
/wp-content/.*googleplus\.gif
/wp-content/.*instagram\.png
/wp-content/.*twitter\.jpg
/wp-content/.*Twitter\.png
/wp-content/.*youtube\.gif
/wp-content/.*youtube\.png
/wp-content/plugins/advanced-facebook-content-locker/.*
/wp-followme/.*
/wp-images/facebook\.png
/wp-images/twitter\.png
/wp-social-toolbar/.*
/wpsocial\.
/xsocial-icons\.
/xsocial_sprites_
/yahoo_16\.
/yahoobuzz\.
/you-tube-1\.
/you-tube-icon\.
/you-tube\.jpg
/Youicon\.
/youtube+icon\.
/youtube-32x32\.
/youtube-48\.
/youtube-button\.
/Youtube-Buttons\.
/youtube-custom-
/youtube-Custom\.
/youtube-follow\.
/YouTube-Home\.
/Youtube-icon-
/youtube-icon\.
/Youtube-icon_
/youtube-logo-
/youtube-over\.
/youtube-small\.
/youtube-space\.
/youtube\.png
/youtube\.svg
/youtube1\.png
/youtube2\.gif
/youtube2\.png
/youtube_16\.
/youtube_18x18_
/youtube_32\.
/youtube_32x
/YouTube_36\.
/youtube_48\.
/youtube_64\.
/youtube_connect\.
/youtube_follow\.
/youtube_ico\.
/youtube_icon-
/youtube_icon\.
/youtube_icon_
/youtube_small\.
/youtube_square\.
/youtubebadge\.
/youtubebutton\.
/youtubeFooterIcon-
/youtubeIcon\.
/youtubesquare\.
/yt-icon1\.
/ytwitter_widget_
=googleplus_icon\.
=socialtags\.
=xing_icon\.
_bottom_google\.
_bottom_linkedin\.
_bottom_vimeo\.
_btn_facebook\.
_btn_like_
_BTN_LinkedIn_
_btn_twitter\.
_delicious\.gif
_delicious_btn\.
_digg\.gif
_email_social_
_facebook-
_facebook01\.
_facebook14\.
_facebook_24\.
_facebook_32\.
_facebook_badge\.
_facebook_btn\.
_facebook_icon\.
_Facebook_Icon_
_facebook_main\.
_facebook_small\.
_facebook_social_
_facebook_white\.
_FacebookIcon\.
_facebooklogo\.
_fb_icon\.
_fb_like\.
_fb_logo\.
_fbshare\.
_files/facebook_
_files/Twitter_
_follow_icon\.
_FollowUs\.
_followus_
_footer_fb\.
_footer_gplus\.
_footer_share_
_footer_twitter\.
_fullimage_Pinterest\.
_fullimage_Twitter\.
_fullimage_YouTube\.
_g+_icon\.
_google_social_
_googleplus-16\.
_googleplus-32\.
_googleplus\.
_googleplus_32\.
_googleplus_logo\.
_googleplus_white\.
_gplus\.png
_Gplus_Logo\.
_header_share\.
_ico_facebook\.
_ico_twitter\.
_ico_youtube\.
_icon-facebook\.
_icon-twitter\.
_icon_blog\.
_icon_facebook_
_icon_fb\.
_icon_google_
_icon_insta\.
_icon_linked_
_icon_linkedin\.
_icon_pinterest\.
_icon_scribd\.
_icon_stumbleupon\.
_icon_technorati_
_icon_tw\.
_icon_twitter_
_icon_youtube\.
_icon_yt\.
_images/social/
_instagram_hover\.
_instagram_icon\.
_Linked_Logo\.
_linkedin-
_linkedin_32\.
_linkedin_icon_
_linkedin_social_
_mvsocialbuttons/
_phone_social_
_pinterest\.gif
_pinterest_icon\.
_pinterest_social_
_pinterest_square_
_pinterest_white\.
_pinteresticon\.
_rssicon\.
_share_bt\.
_share_google\.
_share_icon\.
_share_icon_
_share_icons\.
_share_sprite\.
_share_sprites\.
_share_stumbleupon\.
_share_twitter\.
_share_widget_
_sharebar2_
_ShareIcons\.
_sharelinks_
_slideshare\.
_sns_me2day\.
_sns_twitter\.
_social-google+
_social-media_
_social-sprite\.
_social-twitter\.
_social\.png
_social/images/
_social_32\.
_Social_ALL_
_social_bookmark/
_social_bookmarks/
_social_btns\.
_Social_buttons-
_social_crains\.
_social_email\.
_social_facebook\.
_social_fb\.
_social_flicker\.
_social_footer_
_social_google_
_social_icon\.
_social_icon/
_social_icon2\.
_social_icons\.
_social_icons/
_social_instagram\.
_social_linked_
_social_media_icons_
_social_pinterest\.
_social_shares\.
_social_small\.
_social_sprite\.
_social_twitter\.
_socialBadges\.
_socialbar_
_socialfancysliders/
_SocialIcon_
_socialicons\.
_sociallinks\.
_socialmedia_
_socialmediabox_
_socialmedias2\.
_socials_icons\.
_SocialSprite\.
_socialtoggle\.
_sprite_social\.
_sprite_social_
_stumble_btn\.
_stumble_upon\.
_stumbleupon\.gif
_technorati_24\.
_tumblr_hover\.
_tw_icon\.
_twitter-
_twitter\.gif
_twitter01\.
_twitter3\.
_twitter_24\.
_twitter_btn\.
_twitter_follow\.
_twitter_icon\.
_Twitter_Icon_
_twitter_logo\.
_twitter_small\.
_twitter_social_
_twitter_white\.
_twitterbird_32\.
_twittericon\.
_youtube-button\.
_youTube\.gif
_youtube_32\.
_youtube_channel\.
_youtube_icon\.
_youtube_small\.
_youtube_social_
.aim-ads\.com/multimedia-themonitor-com/wwwroot/.*_twitter_
.bit\.ly/TweetAndTrack\.js
.cloudfront\.net/.*/facebook\.png
.cloudfront\.net/.*/twitter\.png
.diggstatic\.com[/&:?=_].*/follow_buttons/
.rp-api\.com/rjs/repostus\.js
.smartaddon\.com/share_addon\.js
.socialhoney\.co/widget/
.twitter-badges\.s3\.amazonaws\.com[/&:?=_]
.twitter\.com/i/jot
.3dmark\.com/proxycon/images/front-some-fb\.png
.amazingbeautifulworld\.net[/&:?=_].*/images/face\.png
.ana\.net/contentimage/genicon/facebook\.png
.ana\.net/contentimage/genicon/twitter\.png
.australiantimes\.co\.uk/wp-content/uploads/.*_google_pl\.jpg
.bamboobaycondo\.com/uploads/.*/4388939\.png
.bamboobaycondo\.com/uploads/.*/9772065\.png
.bitcoinist\.net/wp-content/.*/fb\.png
.bitcoinist\.net/wp-content/.*/g+\.png
.bitcoinist\.net/wp-content/.*/inst\.png
.bitcoinist\.net/wp-content/.*/yt\.png
.blogspot\.com[/&:?=_].*/facebook\.png
.blogspot\.com[/&:?=_].*/twitter\.png
.burntorangereport\.com/upload/scripts/popup\.js
.bwwstatic\.com/socialtop
.chicagotribune\.com/sn\.php
.cloudfront\.net/facebook/
.cloudfront\.net/facebookpage/
.cloudfront\.net/googleplus/
.cloudfront\.net/instagram/
.cloudfront\.net/linkedin/
.cloudfront\.net/twitter/
.cnet\.com/rest/v1\.0/tweets/
.curate\.venturebeat\.com[/&:?=_]
.dailykostv\.com/digg\.html
.enjin\.com/images/layout/footer-icons\.png
.eurotrucksimulator2\.com/images/logo_blog\.png
.feedsportal\.com/images/bookmark\.gif
.file025\.com/images_mega/ico_tr\.png
.freehostinghero\.com/img/tw\.png
.hollywoodreporter\.com/.*/signup-r-rail
.homedesignlover\.com/wp-content/uploads/.*/pin\.jpg
.htcsource\.com/wp-content/uploads/.*/icons\.png
.huffingtonpost\.com/images/bookmarking/
.hulkshare\.com/facebox\.html
.ibtimes\..*/popup_black\.js
.impactloud\.com/img/follow\.png
.linkis\.com/ajax/get-popup-html
.livescience\.com/likebar\.php
.livescience\.com/social\.php
.marketingsherpa\.com/Zlatko/facebook\.jpg
.marketingsherpa\.com/Zlatko/in\.jpg
.moltenusa\.com/images/com_connecton\.gif
.monova\.org/ajax/get_lightbox_content
.mybetting\.co\.uk/facebook\.png
.mybetting\.co\.uk/twitter\.png
.newsarama\.com/social\.php
.phoronix\.com/.*/facebook\.png
.phoronix\.com/.*/googlep\.png
.phoronix\.com/.*/twitter\.png
.presstv\.ir/images/sn_
.rackcdn\.com/Instagram/
.safewow\.com[/&:?=_].*/faceback\.png
.schwalbe\.co\.uk/_webedit/cached-images/172-37-38-0-0-37-38
.schwalbe\.co\.uk/_webedit/cached-images/174-37-38-0-0-37-38
.seocentro\.com/bookmark/
.sheknows\.com/api/module\?id=follow_social
.social\.dw\.de[/&:?=_]
.sourceforge\.net/social/
.store\.yahoo\.net/lib/directron/icons-test02\.jpg
.theecologist\.org/siteimage/scale/0/0/132471\.gif
.theecologist\.org/siteimage/scale/0/0/132472\.gif
.theecologist\.org/siteimage/scale/0/0/132473\.gif
.valuewalk\.com[/&:?=_].*/fb\.png
.valuewalk\.com[/&:?=_].*/google\.png
.vidyarthiplus\.com/js/launch\.js
.webopedia\.com/img/header_icon_google\.png
.winhelponline\.com/facebook\.png
.wordpress\.com[/&:?=_].*/facebook\.png
.wordpress\.com[/&:?=_].*/twitter1\.png
/jiathis_share\.
.getjoys\.com/js/popup\.js\?v=
.share\.baidu\.com[/&:?=_]
.apfel-faq\.de/name\.js
.chip\.de[/&:?=_].*/fanconverter\.js
.dict\.cc/img/fbplus1\.png
.die-kopie\.info/bilder/facebook\.png
.nibelungenkurier\.de/t-ticker/
.rtl\.de/fb/
.sanoma\.nl/media/static/images/icon_zienl\.png
.spynews\.ro/templates/default/img/face\.png
.nioutaik\.fr/themes/freshy/images/facedebouc\.gif
.nioutaik\.fr/themes/freshy/images/googlepeuluss\.gif
.nioutaik\.fr/themes/freshy/images/zoiseau\.gif
.nouvelobs\.com/social/
.tn-sport\.net/like/
{ +filter{fanboy-social} }
*
{ -block }
.pollland\.nl[/&:?=_].*/share/js/jquery
.static\.autojunk\.nl/javascript/SocialMedia\.js
.nextinpact\.com/js/socialbar\.js
.3dmark\.com/proxycon/images/fb_icon\.png
.4game\.com[/&:?=_].*/facebook\.js
.4game\.com[/&:?=_].*/twitter\.js
.4shared\.com/images/icons/social-connect-buttons\.png
.about\.me[/&:?=_].*/googleplus\?
.acceptableads\.org/images/manifesto/reddit\.png
.accountkiller\.com/i/social-icons\.png
.adblockplus\.org[/&:?=_].*/images/manifesto/reddit\.png
.addthiscdn\.com[/&:?=_].*/print\.png
.afterglowplayer\.com/img/feat_youtube\.jpg
.akamai\.net[/&:?=_].*/social/avatars/
.alienwarearena\.com/bundles/spoutlet/js/SocialShare\.min\.js
.alkoblog\.de/wp-content/plugins/StickySocialBar/js/sharefront\.js\?
.allfacebook\.de/wp-content/uploads/.*/nl-allfacebook\.png
.allocine\.fr[/&:?=_].*/picto_social\.png
.amazonaws\.com/mibbit/gfx/youtube\.png
.amctv\.com[/&:?=_].*/social-buttons\.js
.androidpit\.info/userfiles/.*image/youtube-logo-
.aol\.com[/&:?=_].*/sharrre\.js
.apple\.com/kb/resources/images/i_facebook\.png
.asos\.com/Content/images/.*-ico
.auth\.opera\.com/css/img/icons-social\.png
.avgthreatlabs\.com[/&:?=_].*/facebook-logo\.png
.azurewebsites\.net/Plugins/ExternalAuth\.Facebook/Content/images/facebook-signing\.png
.bitcoinmagazine\.com/wp-content/plugins/.*/social-media-widget/social_widget\.css
.bittorrent\.com/public/min/index\.php\?ipbv=.*/socialicons\.css
.breakoutlist\.com/assets/pinterest-logo\.png
.breakoutlist\.com/assets/twitter-logo\.png
.cdn-immedia\.net/img/share/
.chrisblattman\.com/wp/wp-content/plugins/social/assets/social\.png
.cinemablend\.com/timthumb\.php\?src=/images/facebook/
.classicvalve\.ca/images/slideshow/.*_tumblr\.jpg
.cloudfront\.net/liveblog/modules/login/images/social_icons\.png
.cloudfront\.net/s/images/facebook-login\.png
.cloudfront\.net/s/images/twitter-signin\.png
.cloudfront\.net[/&:?=_].*/signin_with_facebook\.png
.clubs\.nfl\.com/nfl-assets/js/social-buttons\.js
.copdfoundation\.org/Portals/_default/Skins/COPDF/images/social-1\.jpg
.crowdin\.net/images/social/
.dadaviz\.com/static/bower_components/core-icons/social-icons\.html
.daddydesign\.com/.*/wp-social-toolbar/
.discountsstory\.com/image/facebook_icon\.png
.dmi\.dk[/&:?=_].*/jquery_cookie\.js
.draw\.io/images/google-drive-logo\.svg
.eceplayground\.com[/&:?=_].*/plugins/sociable/
.eleximg\.com/.*/tmp/hot/Facebook\.gif
.elle\.com/cm/elle/images/Zd/elle-01-trail-by-twitter-tweet-h-lgn\.jpg
.elliegoulding\.com/images/home/tweetButton\.png
.envoy\.com/images/.*/reddit\.png
.fark\.net/images/.*/links/
.fdcdn\.co\.uk/img/icons/
.filmstarts\.de[/&:?=_].*/picto_social\.png
.foreignpolicy\.com[/&:?=_].*/sharrre\.js
.foreignpolicy\.com[/&:?=_].*_id_twitter_icon\.png
.fyre\.co/.*/facebook_share_post\.png
.gannett-cdn\.com[/&:?=_].*/googleplus-user-account\.js
.ge\.tt/s/images/twitter-extension-icon\.png
.ge\.tt/s/images/twitter-signin\.png
.gearbest\.com/imagecache/.*/images/styleimg/share\.png
.ghacks\.net/wp-content/uploads/.*/google-plus-
.github\.io[/&:?=_].*/icons/social_
.golem\.de/_img/btn-follow-
.golem\.de/staticrl/images/icons-social\.png
.golem\.de/staticrl/images/social_flattr_
.google\..*-youtube\.jpg
.google\..*/gplus-64\.png
.google\..*/retailer_google\.png
.google\.com/analytics/images/.*_social\.png
.google\.com/analytics/images/social\.png
.handmadebydominos\.com[/&:?=_].*/socialShare\.js
.hd-trailers\.net/images/youtube\.png
.hrwiki\.org[/&:?=_].*/youtube\.png
.huffpost\.com/assets/js\.php\?.*-pinterest\.js
.huffpost\.com/images/social-profile/lightbox/snn_lightbox_close\.png
.hypetrak\.com/images/.*facebook
.hypetrak\.com/images/.*twitter
.ignimgs\.com[/&:?=_].*/social/avatars/
.imdb\.com[/&:?=_].*/facebook-button-small\.png
.imgur\.com/images/access/third-party-.*\.png
.immowelt\.de/_scripts/iwag/socialmedia/
.inkscape\.org/design/images/logo_twitter\.png
.inoreader\.com/images/login/but_facebook\.png
.jailbreakqa\.com/m/default/media/images/openid/
.joinsnapcard\.com/thema/img/reddit\.png
.jrjimg\.cn/js\.do\?f=/share/js/
.kpopstarz\.com[/&:?=_].*/ic_comment_facebook\.png
.last\.fm/flatness/partners/facebook_32x32\.png
.lastpass\.com/images/vault/share\.png
.lemaker\.org/uploadfile/icon/google\.jpg
.letsencrypt\.org/images/.*-logo\.png
.lifetricks\.com/wp-content/plugins/nextend-facebook-connect/
.livescience\.com/images/site/social/footer_.*\.gif
.megabus\.com/images/megabus-socialmedia-
.mhfreq\.org/wp-content/uploads/.*/tweet\.png\?
.mlb\.com/bundle\?.*/facebook_button\.css
.mlgflappybird420\.com/images/fb\.png
.modernnotion\.com[/&:?=_].*/EmailShare\.min\.js
.modernnotion\.com[/&:?=_].*/FacebookShare\.min\.js
.modernnotion\.com[/&:?=_].*/SocialLinks\.min\.js
.msfn\.org[/&:?=_].*/facebook_like_box\.css
.mywot\.net/sites/all/themes/wot/images/social-button-sprites\.png
.nationbuilder\.com[/&:?=_].*/signin_with_facebook\.png
.ndtv\.com/css/Widget/comment/images/comment-share-icons\.png
.ndtv\.com/social/static/comment-share-icons\.png
.news\.nationalpost\.com[/&:?=_].*/twitter2\.jpg
.newsday\.com/build/social_media_footer\.min\.js
.nexoneu\.com/common/icon-fb\.gif
.notebookcheck\.com[/&:?=_].*/jquery\.socialshareprivacy\.min\.js
.nouvelobs\.com/sites/all/themes/rue89base/css/img/share/bg-tools\.png
.ogdownloaderapk\.com/images/og-youtube\.png
.panzi\.github\.io/SocialSharePrivacy/
.passets-cdn\.pinterest\.com[/&:?=_]
.patreon\.com/images/fb_login_large\.png
.pcinpact\.com/js/socialbar\.js
.physicsgalaxy\.com/images/SignInWithfacebook\.png
.picozu\.com/r/images/windows/intro/facebook\.png
.pioneerelectronics\.com/piocda/templates/.*\.svg
.playkeepout\.com/img/common/sharing/
.plus\.im/static/img/facebook\.png
.plus\.im/static/img/facebook_over\.png
.pokemon-gl\.com/share/js/
.popsters\.ru/assets/images/fb-login-btn\.png
.popsters\.ru/assets/images/graph/share\.png
.popsters\.ru/assets/landing/images/logos/fb\.png
.popsters\.us/assets/images/fb-login-btn\.png
.popsters\.us/assets/images/graph/share\.png
.popsters\.us/assets/landing/images/logos/fb\.png
.projectevolove\.com/application/themes/clean/images/with_facebook\.png
.quilt\.janrain\.com/.*/linkedin\.png
.qz\.com/images/buttons/sign-in-with-twitter\.png
.redbullusa\.com[/&:?=_].*/socialmedia/
.redcarpetrampage\.com/game/images/facebookbutton
.reddit\.com/mobile/site/images/btn_google_play\.svg
.reformgovernmentsurveillance\.com/images/resized-icons/
.ren-tv\.com/img/images/social/icoFb\.png
.ren-tv\.com/img/images/social/icoVk\.png
.robinlinus\.github\.io/socialmedia-leak/demo\.js
.rorr\.im/static/images/reddit-icon\.png
.s7\.addthis\.com[/&:?=_].*/addthis_widget\.js.*pubid=
.schluetersche\.de/global/js/libs/jquery/plugins/socialshareprivacy/jquery\.socialshareprivacy\.min\.js
.scribblelive\.com/liveblog/modules/login/images/social_icons\.png
.search\.us\.com/resources/img/facebook_btn\.png
.secondhandsongs\.com/art/icons/youtube\.png
.seeklogo\.com/images/.*-seeklogo\.com\.gif
.skiddoo\.com\.au/min/.*/social-buttons\.css
.slacker\.com/.*/google/google-plus-sign-in\.png
.slacker\.com[/&:?=_].*/twitter-top-sprite\.png
.solidopinion\.com/wp-content/.*/social\.jpg
.spardaspendenwahl\.de[/&:?=_].*/jquery\.socialshareprivacy\.min\.js
.sputnik\.md/min/js/plugins/social-likes\.min\.js
.sputniknews\.com/min/js/plugins/social-likes\.min\.js
.stackexchange\.com/content/img/share-sprite-new\.png
.stackoverflow\.com/content/img/share-sprite-new\.png
.static\.canva\.com/designThumbnails/pinterest\.png
.t3n\.de/news/wp-content/uploads/.*/social_media_
.tegna-tv\.com[/&:?=_].*/googleplus-user-account\.js
.telia\.se/tse/js/socialmedia/
.theinterview-movie\.com/images/btn_youtube\.png
.themobileplaybook\.com/assets-v2/images/google-mobile-playbook.*\.png
.themobileplaybook\.com/assets-v2/images/share\.png
.thrusto\.com/images/fb-icon\.png
.thrusto\.com/images/google+\.png
.thrusto\.com/images/login-with-facebook\.png
.timecatcher\.github\.io/img/facebook\.png
.tinydeal\.com/Images/follow_us\.png
.triangleoffense\.com[/&:?=_].*/triangle-offense-header-social-sprites\.png
.tripit\.com/js/tripit/social/
.tunestotube\.com/images/btn_google_signin_dark_normal_web\.png
.tunestotube\.com/images/mp3toyoutube\.png
.tv-kino\.net/wp-content/plugins/fb-traffic-pop/
.twitlonger\.com/images/sign-in-with-twitter\.png
.underverse\.su/min/index\.php.*/js/share42\.js
.upwork\.com[/&:?=_].*/logo-pinterest\.svg
.viewbug\.com[/&:?=_].*/fb_button\.png
.vk\.com/js/al/sharebox\.js
.vk\.me/js/al/sharebox\.js
.wat\..*/assets/images/common/fbsubscribe\.jpg
.weather\.com/cssRollup\?
.weather\.com/jsRollup\?
.weser-kurier\.de/stellen/riot-utils/joined\.js\?.*/socialshareprivacy/
.whitton\.xyz/images/facebookxss/
.womansday\.com/cm/shared/social/social_tools-LL\.js
.wordpress\.com/connect/googleplus-sign-in\.js
.workflowy\.com[/&:?=_].*/hatching_twitter\.png
.workflowy\.com[/&:?=_].*/twitter_logo\.png
.wp\.com/ogyoutube\.ogdownloaderapk\.com[/&:?=_].*/og-youtube\.png
.wp\.com/wp-content/mu-plugins/post-flair/sharing/images/icon-facebook\.png
.wp\.com/wp-content/mu-plugins/post-flair/sharing/images/icon-twitter\.png
.wphub\.com/wp-content/uploads/2010/05/design-freebies-vector-social-icon-set1-138x98\.png
.wwe\.com[/&:?=_].*/btn_facebook_
.www\.google\..*/images/.*google\.png
.www\.google\..*/images/.*googleplus\.png
.www\.google\..*/tv/images/.*youtube\.png
.www\.google\..*/tv/images/youtube\.jpg
.xda-developers\.com[/&:?=_].*/google-plus-login-small\.png
.xssposed\.org/images/design/sign-in-with-twitter-gray\.png
.yastatic\.net/share2/share\.js
.yougetsignal\.com/img/.*_igoogle\.gif
.zillowstatic\.com/.*-social-share-
.aquest\.it/images/aq_facebook\.jpg
.evil-icons\.io/assets/images/social\.png
.grouek\.com/images/fb\.jpg
.hackingui\.com/wp-content/themes/hackingui/images/fb-logo\.jpg
.material\.cmiscm\.com/images/share\.png
.privacypal\.co/assets/img/fb\.jpg
.volkswagen-electrique\.fr/img/share/share\.jpg
{ -block +handle-as-image }
/static/themes/.*/img/icons/.*
.agar\.io/mc/img/Facebook_
.agar\.io/mc/img/FB_Arrow\.png
.agar\.io/mc/img/Twitter_
.akamaihd\.net/r/tedcdnpf-a\.akamaihd\.net/images/playlists/social_
.alloyentertainment\.com/wp-content/.*/thumbs/
.alternativeto\.net/dist/icons/
.amazonaws\.com/images/
.amazonaws\.com/img/facebook_small\.
.androidpolice\.com/wp-content/.*_facebook-
.androidpolice\.com/wp-content/themes/ap2/ap_resize/ap_resize\.php\?.*_Twitter-
.bluejeans\.com[/&:?=_].*/images/auth/
.bronchiectasisandntminitiative\.org[/&:?=_].*/SocialLibrary/
.buzzfeed\.com/buzzfeed-static/static/
.ccm2\.net/www\.commentcamarche\.net/sites/images/
.cdn\.pinknews\.co\.uk/images/
.cdnslate\.com[/&:?=_].*/social/colored-social-
.curelost\.com/logo/
.darkpatterns\.org/images/.*Facebook
.dataknet\.com/css/img/icon/
.depositphotos\.com[/&:?=_].*/depositphotos_
.deskmodder\.de/blog/wp-content/uploads/
.disquscdn\.com[/&:?=_].*/social-icons
.donttrack\.us/images/google-
.downloads\.2kgames\.com[/&:?=_].*/images/
.eff\.org/sites/
.explainxkcd\.com/wiki/images/
.feedburner\.google\.com[/&:?=_]
.freeonlineseo\.org/theme/default/
.freshdesk\.de/themes/freshdesk/images/icons/social-
.getmyapp\.link/content/images/share/
.gigya\.com/gs/i/shareBar/icons/
.gilt\.com/images/share/
.giltcdn\.com/images/share/uploads/
.git-scm\.com/images/company-project-logos/
.google\..*/images/.*/social/
.google\..*/images/google-
.googlecode\.com/hg/icons/
.googlewatchblog\.de/wp-content/uploads/
.gstatic\.com/.*/notifications/logo/google-plus-
.hulu\.com/images/btn-facebook
.iconizer\.net/files/.*_social_
.iconpedia\.net/uploads/
.iconspedia\.com/icon/
.instantlogosearch\.com/svg/
.ix\.de/imgs/.*/linkedin-
.ix\.de/scale/geometry/.*/linkedin-
.kcrw\.com[/&:?=_].*/images/social-icons-
.lastmenonearth\.com/wp-content/.*-social-
.marketplace\.cdn\.mozilla\.net/media/fireplace/img/icons/brands/social-
.media-cache.*\.pinimg\.com[/&:?=_]
.msecnd\.net/resources/gfx/openid/
.neowin\.net/images/uploaded/
.opendatacity\.de/prism/assets/img/logos/logo_facebook_
.play\.ludigames\.com[/&:?=_].*/pc_share_
.prism-break\.org/assets/img/
.rantlifestyle\.com/wp-content/.*facebook
.rantlifestyle\.com/wp-content/.*twitter
.rfi\.fr/sites/all/modules/maison/aef_boulangerie/
.s-media.*\.pinimg\.com[/&:?=_]
.s3\.amazonaws\.com/digital/social-media-part-.*/images/social-media-part-
.setself\.com/content/images/authbox/
.sevego\.com/Img/
.sk-static\.com[/&:?=_].*/fb-logo-
.slidesharecdn\.com[/&:?=_].*/linkedin-
.softicons\.com/download/
.softpedia-static\.com/images/.*-Google-plus-
.spiceworks\.com/assets/community/icons/social/
.spiceworks\.com/assets/community/join/
.ssl-images-amazon\.com/images/.*/socialmedia/
.ssl-images-amazon\.com/images/G/01/socialmedia/sweeps/
.stadt-bremerhaven\.de/wp-content/themes/.*-facebook\.
.stadt-bremerhaven\.de/wp-content/uploads/.*/Facebook_
.stadt-bremerhaven\.de/wp-content/uploads/.*_twitter-
.symantec\.com/content/.*/about/images/social/b-
.techfrag\.com/wp-content/uploads/.*/youtube-
.tipranks\.com/social-auth/images/buttons/
.twimg\.com/client_application_images/
.twimg\.com/profile_images/
.vice\.com/images/.*-social-media-
.visuals\.feedly\.com[/&:?=_].*/resize\?url=
.wappalyzer\.com/sites/default/files/icons/
.wips\.com/www/images/Admin/Create/
.www\.google\..*/landing/now/images/integrations/
.xkcd\.com/comics/
.yourport\.com/logos/
.zaphod\.uk\.vvhp\.net/image/social_network/
.zdnet\.de/wp-content/uploads/.*-logo-
